name: Deploy App Dev

on:
  workflow_call:
    inputs:
      image-version:
        type: string
        description: image version to deploy
        required: true
  workflow_dispatch:
    inputs:
      namespace:
        description: 'K8S namespace for deployment'
        default: 'plendy'
        required: false
        type: string

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      namespace: ${{ inputs.namespace }}
      image-version: ${{ inputs.image-version }}
