name: Deploy App Dev

on:
  push:
    branches:
      - 'main'
    tags:
      - '*-dev-*'
  workflow_dispatch:
    inputs:
      namespace:
        description: 'K8S namespace for deployment'
        default: 'plendy-dev'
        required: false
        type: string

jobs:
  build-publish:
    uses: ./.github/workflows/build.yml
    with:
      push: true
    secrets: inherit

  deploy:
    needs: [build-publish]
    uses: ./.github/workflows/deploy.yml
    with:
      namespace: ${{ inputs.namespace || 'plendy-dev' }}
      values-path: .pressf/k8s/values.dev.yaml
    secrets:
      kube-config: ${{ secrets.KUBE_CONFIG_DEV }}