name: dotnet-build

on:
  inputs:
    dotnet-version:
      description: 'The dotnet version to use'
      default: '6.0.x'
      required: false
  secrets:
    nuget-pat:
      required: true

jobs:
  dotnet_build:
    name: Builds source code
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Configure nuget
        run: dotnet nuget add source https://nuget.pkg.github.com/pressfio/index.json --name "pressfio" --username "pressfio-bot" --password ${{ secrets.nugetPAT }}
        shell: bash

      - name: Restore project
        run: dotnet restore
        shell: bash

      - name: Build project
        run: dotnet publish -c Release -o ${{ github.event.repository.name }}
        shell: bash
