name: dotnet-build
description: Builds dotnet project
inputs:
  dotnet-version:
    description: 'The dotnet version to use'
    default: '6.0.x'
    required: false
  project-path:
    description: 'The path to the project'
    required: true

runs:
  using: composite
  steps: 
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Configure nuget
      run: dotnet nuget add source https://nuget.pkg.github.com/pressfio/index.json --name "pressfio" --username "pressfio-bot" --password "${{ secrets.NUGET_REPO_TOKEN }}"
      shell: bash

    - name: Restore project
      run: dotnet restore
      shell: bash

    - name: Build project
      run: dotnet publish -c Release -o ${{ github.event.repository.name }}
      shell: bash