service:
  name: 'sentinel'
  args: ['api']
  replicas: 1
  migrations:
    enabled: true
  ports:
    grpc: true
    internal: true
    diag: true
  env:
    - name: LOG_LEVEL
      value: TRC
    - name: GRPC_GO_LOG_FORMATTER
      value: json
    - name: GRPC_GO_LOG_SEVERITY_LEVEL
      value: info
    - name: GRPC_GO_LOG_VERBOSITY_LEVEL
      value: '99'
    - name: GRPC_INTERNAL_GO_LOG_FORMATTER
      value: json
    - name: GRPC_INTERNAL_GO_LOG_SEVERITY_LEVEL
      value: info
    - name: GRPC_INTERNAL_GO_LOG_VERBOSITY_LEVEL
      value: '99'
    - name: GRPC_INTERNAL_LISTEN_PORT
      value: '5001'
    - name: DB_TYPE
      value: pg
    - name: DB_HOST
      value: postgres-postgresql.persistence.svc.cluster.local
    - name: DB_DATABASE
      value: sentinel-rc
    - name: DB_USER
      value: sentinel
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: db-password
    - name: DB_MASTER_DATABASE
      value: postgres
    - name: DB_MASTER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: db-master-password
    - name: DB_MASTER_USER
      value: postgres
    - name: JWT_ACCESS_TOKEN_RSA_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: jwt-access-token-rsa-private-key
    - name: JWT_REFRESH_TOKEN_HMAC_KEY
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: jwt-refresh-token-hmac-key
    - name: APPLE_SIGN_IN_JWT_SIGNATURE_CONTENT
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-jwt-signature-content
    - name: APPLE_SIGN_IN_KEY_ID
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-key-id
    - name: APPLE_SIGN_IN_JWT_ISSUER
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-key-jwt-issuer
    - name: DB_MIGRATION_DEPLOY_JOB_ID
      value: rc
    - name: DB_MIGRATION_DRY_RUN
      value: 'false'      

grpcIngress:
  enabled: true
  host: rc.sentinel.plendy.app