service:
  name: 'sentinel'
  args: ['api']
  replicas: 1
  ports:
    grpc: true
    diag: true
  env:
    - name: LOG_LEVEL
      value: TRC
    - name: GRPC_GO_LOG_FORMATTER
      value: json
    - name: GRPC_GO_LOG_SEVERITY_LEVEL
      value: info
    - name: GRPC_GO_LOG_VERBOSITY_LEVEL
      value: '99'
    - name: DB_DATABASE
      value: sentinel
    - name: sentinel.svc
      value: '6831'
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: db-password
    - name: DB_TYPE
      value: pg
    - name: DB_USER
      value: sentinel
    - name: DB_MASTER_DATABASE
      value: postgres
    - name: DB_MASTER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: db-master-password
    - name: DB_MASTER_USER
      value: postgres
    - name: JWT_ACCESS_TOKEN_RSA_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: jwt-access-token-rsa-private-key
    - name: JWT_REFRESH_TOKEN_HMAC_KEY
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: jwt-refresh-token-hmac-key
    - name: APPLE_SIGN_IN_JWT_SIGNATURE_CONTENT
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-jwt-signature-content
    - name: APPLE_SIGN_IN_KEY_ID
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-key-id
    - name: APPLE_SIGN_IN_JWT_ISSUER
      valueFrom:
        secretKeyRef:
          name: plendy-secrets
          key: asi-key-jwt-issuer

grpcIngress:
  enabled: true
  host: rc.sentinel.plendy.app