name: deploy-helm-staging
description: Deploys project as Helm chart
inputs:
  namespace:
    description: 'K8S namespace for deployment'
    default: 'plendy'
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.9.3

    - name: Add Plendy Helm repo
      run: helm repo add pressfio https://pressfio.github.io/helm
      shell: bash

    - name: Preview
      run: |
          helm template  \
            ${{ inputs.release-name }} pressfio \ 
            --debug
            --atomic \
            --timeout 1m \ 
            --values .plendy/values.yaml \
            --namespace ${{ inputs.namespace }} \ 
            --create-namespace 
      shell: bash

    - name: Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: alexsem80
        minimum-approvals: 1
        issue-title: "Deploying to staging"

    - name: Install chart
      run: |
          helm upgrade \
            ${{ inputs.release-name }} pressfio \ 
            --install \
            --atomic \
            --timeout 1m \ 
            --values .plendy/values.yaml \
            --namespace ${{ inputs.namespace }} \ 
            --create-namespace 
      shell: bash

