name: Build and publish builder

on:
  push:
    tags:
      - 'builder/*'

env:
  CONTAINER_REGISTRY: ghcr.io
  ACTOR: pressfio-bot

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps: 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU dependency
      uses: docker/setup-qemu-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.ACTOR }}
        password: ${{ secrets.BOT_SECRET }}

    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build and publish image
      env:
        BOT_SECRET: ${{ secrets.BOT_SECRET }}
        TARGET_PLATFORMS_LIST: ${{ inputs.target_platforms_list }}
      working-directory: builder
      run: make build
      shell: bash