name: Build Builder (linux/amd64)

on:
  push:
    tags:
      - 'builder/*'

env:
  BUILDER_PLATFORM: linux/amd64

jobs:
  setup-docker:
    uses: ./.github/workflows/build.yml
  
  build-builder:
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ vars.BUILDER_PLATFORM }}
    secrets: inherit