name: Deploy Loki+Grafana

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'K8S namespace for deployment'
        default: 'observability'
        required: true
        type: string

jobs:
  deploy-loki-grafana:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.9.3

    - name: Add Bitnami repo
      run: helm repo add bitnami https://charts.bitnami.com/bitnami
      shell: bash

    - name: Update Bitnami Helm repo
      run: helm repo update bitnami
      shell: bash

    - name: Install Loki
      run: |
        helm upgrade \
          --install \
          --atomic \
          --timeout 3m \
          --values infra/observability/loki/values.yaml \
          --namespace ${{ inputs.namespace }} \
         loki bitnami/grafana-loki
      shell: bash

    - name: Install Grafana
      run: |
        helm upgrade \
          --install \
          --atomic \
          --timeout 3m \
          --values infra/observability/grafana/values.yaml \
          --namespace ${{ inputs.namespace }} \
          --set admin.password=${{ secrets.GRAFANA_PASSWORD }} \
         grafana bitnami/grafana
      shell: bash
    
