name: Deploy PostgreSQL

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'K8S namespace for deployment'
        default: 'persistence'
        required: true
        type: string

jobs:
  deploy-postgres:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.9.3

    - name: Add Bitnami repo
      run: helm repo add bitnami https://charts.bitnami.com/bitnami
      shell: bash

    - name: Update Bitnami Helm repo
      run: helm repo update bitnami
      shell: bash

    - name: Install PostgreSQL
      run: |
        helm upgrade \
          --install \
          --atomic \
          --timeout 1m \
          --values infra/persistence/postgres/values.yaml \
          --namespace ${{ inputs.namespace }} \
          --set global.postgresql.auth.postgresPassword=${{ secrets.POSTGRES_PASSWORD }} \
         postgres bitnami/postgresql
      shell: bash
    
