name: Push Docker Image

on:
  workflow_run:
    workflows: [Build Builder]
    types:
      - completed

jobs:
  push-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set variables
      id: vars
      run: echo "image_tag="`git tag | grep builder | head -n 1 | sed -e 's/builder\///'`"" >> $GITHUB_OUTPUT;
    - name: Push image
      env:
        BUILDER_IMAGE_VERSION: ${{ steps.vars.outputs.image_tag }}
      working-directory: builder
      run: make push
      shell: bash